version: '3.8'

services:
  neo4j:
    container_name: neo4j-5.10.0-community
    image: neo4j:5.10.0-community
    restart: on-failure
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    environment:
      USERNAME: $NEO4J_USERNAME
      PASSWORD: $NEO4J_PASSWORD
    ports:
      - "7474:7474"
    networks:
      - social-network

  crowdparlay-social:
    container_name: crowdparlay-social
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    build:
      context: .
    environment:
      RABBITMQ_AMQP_SERVER_URL: "amqp://$RABBITMQ_USER:$RABBITMQ_PASSWORD@rabbitmq:5672"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5454"
      NEO4J_URI: $NEO4J_URI
      NEO4J_USERNAME: $NEO4J_USERNAME
      NEO4J_PASSWORD: $NEO4J_PASSWORD
    ports:
      - "5454:5454"
    networks:
      - social-network

  rabbitmq:
    container_name: rabbitmq-3.9
    image: rabbitmq:3.9
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - social-network

networks:
  social-network:
    external: true
