openapi: 3.0.1
info:
  title: Crowd Parlay Social API
  description: RESTful API of the Crowd Parlay's Social service.
  version: '1.0'
paths:
  '/api/v1/authors/{authorId}':
    get:
      tags:
        - Authors
      summary: Returns author with the specified ID.
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AuthorDto'
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorDto'
            text/json:
              schema:
                $ref: '#/components/schemas/AuthorDto'
  '/api/v1/comments/{commentId}':
    get:
      tags:
        - Comments
      summary: Returns comment with the specified ID.
      parameters:
        - name: commentId
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommentDto'
            application/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
            text/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
  /api/v1/comments:
    get:
      tags:
        - Comments
      summary: Returns all comments created by author with the specified ID.
      parameters:
        - name: authorId
          in: query
          style: form
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          style: form
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          style: form
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentDto'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentDto'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentDto'
    post:
      tags:
        - Comments
      summary: Creates a comment.
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommentDto'
            application/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
            text/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
  '/api/v1/comments/{targetCommentId}/reply':
    post:
      tags:
        - Comments
      summary: Creates a reply to comment with the specified ID.
      parameters:
        - name: targetCommentId
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommentDto'
            application/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
            text/json:
              schema:
                $ref: '#/components/schemas/CommentDto'
components:
  schemas:
    AuthorDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        displayName:
          type: string
        avatarUrl:
          type: string
          nullable: true
      additionalProperties: false
    CommentDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        author:
          $ref: '#/components/schemas/AuthorDto'
        createdAt:
          type: string
          format: date-time
        replyCount:
          type: integer
          format: int32
        firstRepliesAuthors:
          type: array
          items:
            $ref: '#/components/schemas/AuthorDto'
      additionalProperties: false
    CommentRequest:
      type: object
      properties:
        content:
          type: string
      additionalProperties: false