name: Deploy API documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-doc:
    if: ${{ github.event_name != 'pull_request' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    env:
      COMMON_OPENAPI_CONTENT: |
        openapi: 3.0.1
        info:
          title: Crowd Parlay API
          description: Crowd Parlay's RESTful API.
          version: 'v1'
        servers:
          - url: https://crowdparlay.com
            description: Production
    steps:
      - name: Produce common.yaml
        run: echo "$COMMON_CONTENT" > _common.oapi.yaml
      - name: Download OpenAPIs of all services # ("crowdparlay/users" "crowdparlay/social")
        run: |
          repos=("crowdparlay/social")
          for repo in "${repos[@]}"
          do
              echo "Downloading openapi.yaml asset from the latest release of $repo"
              wget -O "openapi/${repo//\//_}.oapi.yaml" "https://github.com/$repo/releases/latest/download/openapi.yaml"
          done
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
      - name: Merge OpenAPI files
        run: redocly join $(ls | grep '\.oapi\.yaml$' | xargs) -o openapi.yaml
      - name: Print openapi.yaml
        run: cat openapi.yaml
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ vars.BUMP_SH_DOCUMENTATION }}
          token: ${{ secrets.BUMP_SH_TOKEN }}
          file: openapi.yaml
